query spacex {
  launchesPast(limit: 10) {
    mission_name
    launch_date_local
    launch_site {
      site_name_long
    }
    links {
      article_link
      video_link
    }
    rocket {
      rocket_name
      first_stage {
        cores {
          flight
          core {
            reuse_count
            status
          }
        }
      }
      second_stage {
        payloads {
          payload_type
          payload_mass_kg
          payload_mass_lbs
        }
      }
    }
    ships {
      name
      home_port
      image
    }
  }
}

# mapforums

type Post {
  id: ID!
  author: User!
  title: String
  content: String!
  answer: [Post]
  type: PostType!
  reply_of: Post.id
  timestamp: DateTime!
}

type User {
  discord_id: ID!
  roblox_id: ID!
  posts: [Post]!
  roles: [Role]!
  votes: [Vote]!
  restricted: Boolean!
}

type Vote {
  Post: Post!
  User: User!
  Cast: VoteCast!
}

type WikiPage {
  id: ID!
  title: String!
  content: String!
  timestamp: DateTime!
  collaborators: [User!]!
  commit_history: 
}

type Commit {
  content: String!
  timestamp: DateTime!
  submitter: User!
  id_to_page: SomePage.id!
}

# Enums

enum VoteCast {
  Upvote
  Downvote
}

# Unions

union SomePage = WikiPage | Post

union PostType = "question" | "answer" | "comment"

union Role = "admin" | "moderator" | "contributor" | "maintainer" | "top contributor" | "rsource developer" | "strafes.net developer" | "knows their shit"
