name: CI
on: push

jobs:
  Lint_Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.17"
      - run: go run hello.go
